name: Deploy to EC2 with Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      - name: Debug - check image
        run: docker images

      - name: Copy Docker image to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "Dockerfile"
          target: "/home/ubuntu/app"

      - name: Run Docker container on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Docker 설치 (필요시)
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker

            # Docker 이미지 빌드 (서버에서)
            docker build -t myapp:latest /home/ubuntu/app

            # 기존 컨테이너 중지 및 삭제
            docker ps -a -q --filter "name=myapp" | xargs --no-run-if-empty docker stop | xargs --no-run-if-empty docker rm

            # 새로운 컨테이너 실행
            docker run -d --name myapp -p 8080:8080 myapp:latest
